site_name: Microscope for Salesforce
docs_dir: docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - About Microscope: MicroscopeAbout.md
  - Solution: MicroscopeSolution.md
  - Installation: installation/MicroscopeInstallation.md
  - Downloads:
    - downloads/microscope-pdf.md
    - downloads/microscope-skills.md
  - Overview Demo: testhtml/microscope-overview.html
