title: Microscope Documentation
theme: just-the-docs

search_enabled: true

mermaid:
  # Version of mermaid to use; see https://mermaid.js.org/
  version: "11"

footer_content: "Microscope Documentation"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
